#!/usr/bin/env bash
# This script prints a message indefinitely and handles signals
PIDFILE="/tmp/myscript.pid"
echo $$ > "$PIDFILE"
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PIDFILE"; exit 0' SIGQUIT SIGTER
while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
