#!/usr/bin/env bash
# This script prints a message indefinitely and handles signals
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT SIGTERM
while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
